In [1]:
# 1. Write a NumPy program to test whether none of the elements of a given array is zero.
import numpy as np

def none_of_elements_is_zero(arr):
    return np.all(arr != 0)

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([1, 2, 0, 4])
arr3 = np.array([0, 0, 0, 0])

print(none_of_elements_is_zero(arr1)) 
print(none_of_elements_is_zero(arr2)) 
print(none_of_elements_is_zero(arr3)) 

True
False
False


In [1]:
# 1. Write a NumPy program to test whether none of the elements of a given array is zero.
import numpy as np

def none_of_elements_is_zero(arr):
    return np.all(arr != 0)

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([1, 2, 0, 4])
arr3 = np.array([0, 0, 0, 0])

print(none_of_elements_is_zero(arr1)) 
print(none_of_elements_is_zero(arr2)) 
print(none_of_elements_is_zero(arr3)) 

True
False
False


In [2]:
# 2. Write a NumPy program to test whether any of the elements of a given array is non-zero.
import numpy as np

def any_element_is_nonzero(arr):
    return np.any(arr != 0)

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([1, 2, 0, 4])
arr3 = np.array([0, 0, 0, 0])

print(any_element_is_nonzero(arr1)) 
print(any_element_is_nonzero(arr2))
print(any_element_is_nonzero(arr3)) 

True
True
False


In [3]:
# 3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given 
import numpy as np

arr1 = np.array([1.0, 2.0, 3.0])
arr2 = np.array([1.0, 2.0, 3.001])

equal = np.all(arr1 == arr2)
equal_within_tol = np.allclose(arr1, arr2, rtol=1e-02, atol=1e-02)

print("Equal:", equal)
print("Equal within tolerance:", equal_within_tol)

Equal: False
Equal within tolerance: True


In [4]:
# 4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.
import numpy as np

zeros_arr = np.zeros(10)
ones_arr = np.ones(10)
fives_arr = np.full(10, 5)

result_arr = np.concatenate((zeros_arr, ones_arr, fives_arr))

print(result_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [5]:
# 5. Write a NumPy program to create an array of the integers from 30 to70.
import numpy as np

result_arr = np.arange(30, 71)
print(result_arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [6]:
# 6. Write a NumPy program to create a 3x3 identity matrix 
import numpy as np

result_arr = np.identity(3)

print(result_arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
# 7. Write a NumPy program to generate a random number between 0 and 1 
import numpy as np

result = np.random.rand()

print(result)


0.2849958799804929


In [8]:
# 8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution 
import numpy as np

np.random.seed(42)

arr = np.random.randn(15)

print(arr)


[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
  1.57921282  0.76743473 -0.46947439  0.54256004 -0.46341769 -0.46572975
  0.24196227 -1.91328024 -1.72491783]


In [9]:
# 9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.
import numpy as np

vector = np.arange(15, 56)

print(vector[1:-1])


[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [10]:
# 10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10
import numpy as np

vector = np.random.randint(0, 11, size=5)

print(vector)


[10  9  2  6  3]


In [11]:
# 11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.
import numpy as np

matrix = np.zeros((10, 10))

matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1

print(matrix)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [12]:
# 12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.
import numpy as np

matrix = np.zeros((5, 5))

np.fill_diagonal(matrix, [1, 2, 3, 4, 5])

print(matrix)


[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [13]:
# 13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.
import numpy as np

matrix = np.zeros((4, 4))

matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1

print(matrix)


[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [14]:
# 14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

np.savez_compressed('my_arrays.npz', arr1=arr1, arr2=arr2)

with np.load('my_arrays.npz') as data:
    loaded_arr1 = data['arr1']
    loaded_arr2 = data['arr2']

print('Array 1:', loaded_arr1)
print('Array 2:', loaded_arr2)


Array 1: [1 2 3 4 5]
Array 2: [ 6  7  8  9 10]


In [15]:
# 15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. Select 
import numpy as np

rand_array = np.random.rand(40)

selected_values = rand_array[rand_array > 0.5]

print(selected_values)


[0.59241457 0.60754485 0.94888554 0.96563203 0.80839735 0.68423303
 0.9093204  0.66252228 0.52006802 0.54671028 0.96958463 0.77513282
 0.93949894 0.89482735 0.59789998 0.92187424 0.82873751 0.54269608
 0.80219698]


In [16]:
# 16. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number
import numpy as np

arr = np.array([1, 3, 5, 7, 9, 2, 4, 6, 8])

num = 5

less_than_num = arr[arr < num]

greater_than_num = arr[arr > num]

print('Numbers less than {}:'.format(num), less_than_num)
print('Numbers greater than {}:'.format(num), greater_than_num)


Numbers less than 5: [1 3 2 4]
Numbers greater than 5: [7 9 6 8]
